function [fitresult, gof] = curveFit(xp, yp)
%CREATEFIT(XP,YP)
%  Create a fit.
%
%  Data for 'Peak Intensity Fit' fit:
%      X Input : xp
%      Y Output: yp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Mar-2016 14:02:17


%% Fit: 'Peak Intensity Fit'.
[xData, yData] = prepareCurveData( xp, yp );

% Set up fittype and options.
ft = fittype( 'poly5' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% UNCOMMENT TO TEST
% Plot fit with data.
% figure( 'Name', 'Peak Intensity Fit' );
% h = plot( fitresult, xData, yData );
% legend( h, 'yp vs. xp', 'Peak Intensity Fit', 'Location', 'NorthEast' );
% % Label axes
% xlabel xp
% ylabel yp
% grid on
end